---
- name: Create Nomad Group
  group:
    name: nomad
    state: present
  when: rpm_bin is failed or apt_bin is failed
  tags:
    - install

- name: Remove Nomad Group
  group:
    name: nomad
    state: absent
  tags:
    - uninstall
