---
- name: Create Nomad User
  user:
    name: "{{nomad_user}}"
    shell: "{{nomad_shell}}"
    home: /etc/nomad.d
    groups: "{{ nomad_groups }}"
    system: "{{user_system}}"
    append: "{{user_append}}"
    state: present
  tags:
    - install

- name: Remove Nomad User
  user:
    name: nomad
    state: absent
    remove: yes
  tags:
    - uninstall