---
- name: nomad manager Config
  template:
    src: manager.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: "0640"
  when: "'manager' in group_names"
  tags:
    - install

- name: nomad worker config
  template:
    src: worker.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: "0640"
  when: "'worker' in group_names"
  tags:
    - install

- name: nomad standalone config
  template:
    src: standalone.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: "0640"
  when: "'standalone' in group_names"
  tags:
    - install

- name: nomad manager Config (encrypt_enabled)
  template:
    src: manager_encrypt.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: "0640"
  when: "'manager_encrypt' in group_names"
  tags:
    - install

- name: Remove Configuration dir
  file:
    path: /etc/nomad.d
    state: absent
  tags:
    - uninstall