---
- name: nomad data dir
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
  tags:
    - install

- name: Remove data dir 
  file:
    path: /opt/nomad
    state: absent
  tags:
    - uninstall