---
- name: Nomad service
  template:
    src: nomad.j2
    dest: /etc/systemd/system/nomad.service
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0640"
  tags:
    - install

- name: Remove Nomad Service
  file:
    path: /etc/systemd/system/nomad.service
    state: absent
  tags:
    - uninstall