---
- name: nomad manager Config
  template:
    src: manager.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0640"
  when: "'manager' in group_names"
  tags:
    - install

- name: nomad worker config
  template:
    src: worker.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0640"
  when: "'worker' in group_names"
  tags:
    - install

- name: Remove Configuration dir
  file:
    path: /etc/nomad.d
    state: absent
  tags:
    - uninstall