---
- name: Create Nomad Group
  group:
    gid: 1001
    name: nomad
    state: present
  tags:
    - install

- name: Remove Nomad Group
  group:
    name: nomad
    state: absent
  tags:
    - uninstall