---
- name: nomad data dir
  file:
    path: /opt/nomad
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
  tags:
    - install

- name: Remove data dir 
  file:
    path: /opt/nomad
    state: absent
  tags:
    - uninstall