---
- name: Create Nomad User
  user:
    name: nomad
    shell: /bin/false
    home: /etc/nomad.d
    groups: ["{{ nomad_groups }}"]
    system: yes
  tags:
    - install

- name: Remove Nomad User
  user:
    name: nomad
    state: absent
    remove: yes
  tags:
    - uninstall