- name: "Installing Debian Unzip"
  apt:
    name: 
      - unzip
    state: latest
    update_cache: true
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - install

- name: "Installing Centos Unzip"
  yum:
    name: 
      - unzip
    state: latest
    update_cache: true
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: 
    - install

- name: stop nomad
  service:
    name: nomad
    state: stopped
    enabled: no
  tags:
    - uninstall